### ISSUE TITLE
Open the quickfix window on any task

### ISSUE THREAD

**Issue by stevenxxiu** [al1-ce/just.nvim#5]
In my `justfile` I have a few tasks. It'll be helpful to open the quickfix window after any task finishes.

**Comment by al1-ce** [comment]
I'll add another option to config soon then!

**Comment by stevenxxiu** [comment]
Oh sorry I mean begins, but thanks, that was a fast reply!

**Comment by al1-ce** [comment]
Yea, it'll be basically as option for run task but gonna apply for everything. Which is that it'll open when you run any task and option is enabled

**Comment by al1-ce** [comment]
Done, sorry took so long, life n stuff haha

**Comment by stevenxxiu** [comment]
No worries, life happens. Thanks so much for implementing this!

**Comment by al1-ce** [comment]
Ofc, I'm happy that someone uses rhis plugin and I'm happy to improve it if needed
