### ISSUE TITLE
Missing `jsfunc` module

### ISSUE THREAD

**Issue by stevenxxiu** [al1-ce/just.nvim#6]
When I updated the plugin after the commit 2fe24f3355bf5b695f3729f93e94fbbe3746a585, I get the error:

    ... .local/share/nvim/lazy/just.nvim/lua/just/init.lua:3: module 'jsfunc' not found:

**Comment by al1-ce** [comment]
Ah! Forgot to update readme

From now on just.nvim *also* depends on "al1-ce/jsfunc.nvim", so you gotta add that dependency

**Comment by stevenxxiu** [comment]
Thanks that explains it! No wonder I searched around a bit and couldn't find this module.
